/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BoundlessVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeLeaseId"
      | "allowedAssets"
      | "allowedProtocols"
      | "consumerName"
      | "controller"
      | "depositToken"
      | "executeProtocolCall"
      | "executeTransfer"
      | "memberBudgetState"
      | "memberPolicies"
      | "operatorName"
      | "owner"
      | "previewExecution"
      | "setAllowedAsset"
      | "setAllowedProtocol"
      | "setController"
      | "setLeaseContext"
      | "setMemberPolicy"
      | "transferOwnership"
      | "withdrawNative"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowedAssetUpdated"
      | "AllowedProtocolUpdated"
      | "ControllerUpdated"
      | "LeaseContextUpdated"
      | "MemberPolicyUpdated"
      | "MemberSpendConsumed"
      | "NativeWithdrawn"
      | "OwnershipTransferred"
      | "ProtocolCallExecuted"
      | "TokenDeposited"
      | "TokenWithdrawn"
      | "TransferExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeLeaseId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowedAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedProtocols",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "consumerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProtocolCall",
    values: [string, string, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransfer",
    values: [
      string,
      string,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "memberBudgetState",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "memberPolicies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operatorName",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewExecution",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedAsset",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedProtocol",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setController",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLeaseContext",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMemberPolicy",
    values: [AddressLike, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeLeaseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedProtocols",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumerName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProtocolCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberBudgetState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operatorName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLeaseContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMemberPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace AllowedAssetUpdatedEvent {
  export type InputTuple = [asset: AddressLike, allowed: boolean];
  export type OutputTuple = [asset: string, allowed: boolean];
  export interface OutputObject {
    asset: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowedProtocolUpdatedEvent {
  export type InputTuple = [protocol: AddressLike, allowed: boolean];
  export type OutputTuple = [protocol: string, allowed: boolean];
  export interface OutputObject {
    protocol: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ControllerUpdatedEvent {
  export type InputTuple = [controller: AddressLike];
  export type OutputTuple = [controller: string];
  export interface OutputObject {
    controller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseContextUpdatedEvent {
  export type InputTuple = [
    leaseId: string,
    consumerName: string,
    operatorName: string
  ];
  export type OutputTuple = [
    leaseId: string,
    consumerName: string,
    operatorName: string
  ];
  export interface OutputObject {
    leaseId: string;
    consumerName: string;
    operatorName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberPolicyUpdatedEvent {
  export type InputTuple = [
    member: AddressLike,
    enabled: boolean,
    perTxUsd6: BigNumberish,
    dailyBudgetUsd6: BigNumberish
  ];
  export type OutputTuple = [
    member: string,
    enabled: boolean,
    perTxUsd6: bigint,
    dailyBudgetUsd6: bigint
  ];
  export interface OutputObject {
    member: string;
    enabled: boolean;
    perTxUsd6: bigint;
    dailyBudgetUsd6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberSpendConsumedEvent {
  export type InputTuple = [
    member: AddressLike,
    requestId: string,
    spentUsd6: BigNumberish,
    remainingDailyUsd6: BigNumberish
  ];
  export type OutputTuple = [
    member: string,
    requestId: string,
    spentUsd6: bigint,
    remainingDailyUsd6: bigint
  ];
  export interface OutputObject {
    member: string;
    requestId: string;
    spentUsd6: bigint;
    remainingDailyUsd6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolCallExecutedEvent {
  export type InputTuple = [
    requestId: string,
    leaseId: string,
    target: AddressLike,
    value: BigNumberish,
    spentUsd6: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    leaseId: string,
    target: string,
    value: bigint,
    spentUsd6: bigint
  ];
  export interface OutputObject {
    requestId: string;
    leaseId: string;
    target: string;
    value: bigint;
    spentUsd6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenDepositedEvent {
  export type InputTuple = [
    token: AddressLike,
    from: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, from: string, amount: bigint];
  export interface OutputObject {
    token: string;
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferExecutedEvent {
  export type InputTuple = [
    requestId: string,
    leaseId: string,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    spentUsd6: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    leaseId: string,
    token: string,
    to: string,
    amount: bigint,
    spentUsd6: bigint
  ];
  export interface OutputObject {
    requestId: string;
    leaseId: string;
    token: string;
    to: string;
    amount: bigint;
    spentUsd6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BoundlessVault extends BaseContract {
  connect(runner?: ContractRunner | null): BoundlessVault;
  waitForDeployment(): Promise<this>;

  interface: BoundlessVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeLeaseId: TypedContractMethod<[], [string], "view">;

  allowedAssets: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  allowedProtocols: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  consumerName: TypedContractMethod<[], [string], "view">;

  controller: TypedContractMethod<[], [string], "view">;

  depositToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeProtocolCall: TypedContractMethod<
    [
      requestId: string,
      leaseId: string,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      spentUsd6: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  executeTransfer: TypedContractMethod<
    [
      requestId: string,
      leaseId: string,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      spentUsd6: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  memberBudgetState: TypedContractMethod<
    [member: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        enabled: boolean;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;

  memberPolicies: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        enabled: boolean;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        spentWindowStartedAt: bigint;
      }
    ],
    "view"
  >;

  operatorName: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  previewExecution: TypedContractMethod<
    [leaseId: string, requestedUsd6: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        allowed: boolean;
        resolvedStatus: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;

  setAllowedAsset: TypedContractMethod<
    [asset: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setAllowedProtocol: TypedContractMethod<
    [target: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setController: TypedContractMethod<
    [nextController: AddressLike],
    [void],
    "nonpayable"
  >;

  setLeaseContext: TypedContractMethod<
    [leaseId: string, nextConsumerName: string, nextOperatorName: string],
    [void],
    "nonpayable"
  >;

  setMemberPolicy: TypedContractMethod<
    [
      member: AddressLike,
      enabled: boolean,
      perTxUsd6: BigNumberish,
      dailyBudgetUsd6: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawNative: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeLeaseId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowedAssets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "allowedProtocols"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "consumerName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "controller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeProtocolCall"
  ): TypedContractMethod<
    [
      requestId: string,
      leaseId: string,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      spentUsd6: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeTransfer"
  ): TypedContractMethod<
    [
      requestId: string,
      leaseId: string,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      spentUsd6: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "memberBudgetState"
  ): TypedContractMethod<
    [member: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        enabled: boolean;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "memberPolicies"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, bigint, bigint, bigint, bigint] & {
        exists: boolean;
        enabled: boolean;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        spentWindowStartedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "operatorName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewExecution"
  ): TypedContractMethod<
    [leaseId: string, requestedUsd6: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        allowed: boolean;
        resolvedStatus: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAllowedAsset"
  ): TypedContractMethod<
    [asset: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowedProtocol"
  ): TypedContractMethod<
    [target: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setController"
  ): TypedContractMethod<[nextController: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLeaseContext"
  ): TypedContractMethod<
    [leaseId: string, nextConsumerName: string, nextOperatorName: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMemberPolicy"
  ): TypedContractMethod<
    [
      member: AddressLike,
      enabled: boolean,
      perTxUsd6: BigNumberish,
      dailyBudgetUsd6: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawNative"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AllowedAssetUpdated"
  ): TypedContractEvent<
    AllowedAssetUpdatedEvent.InputTuple,
    AllowedAssetUpdatedEvent.OutputTuple,
    AllowedAssetUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AllowedProtocolUpdated"
  ): TypedContractEvent<
    AllowedProtocolUpdatedEvent.InputTuple,
    AllowedProtocolUpdatedEvent.OutputTuple,
    AllowedProtocolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ControllerUpdated"
  ): TypedContractEvent<
    ControllerUpdatedEvent.InputTuple,
    ControllerUpdatedEvent.OutputTuple,
    ControllerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseContextUpdated"
  ): TypedContractEvent<
    LeaseContextUpdatedEvent.InputTuple,
    LeaseContextUpdatedEvent.OutputTuple,
    LeaseContextUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MemberPolicyUpdated"
  ): TypedContractEvent<
    MemberPolicyUpdatedEvent.InputTuple,
    MemberPolicyUpdatedEvent.OutputTuple,
    MemberPolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MemberSpendConsumed"
  ): TypedContractEvent<
    MemberSpendConsumedEvent.InputTuple,
    MemberSpendConsumedEvent.OutputTuple,
    MemberSpendConsumedEvent.OutputObject
  >;
  getEvent(
    key: "NativeWithdrawn"
  ): TypedContractEvent<
    NativeWithdrawnEvent.InputTuple,
    NativeWithdrawnEvent.OutputTuple,
    NativeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolCallExecuted"
  ): TypedContractEvent<
    ProtocolCallExecutedEvent.InputTuple,
    ProtocolCallExecutedEvent.OutputTuple,
    ProtocolCallExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TokenDeposited"
  ): TypedContractEvent<
    TokenDepositedEvent.InputTuple,
    TokenDepositedEvent.OutputTuple,
    TokenDepositedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWithdrawn"
  ): TypedContractEvent<
    TokenWithdrawnEvent.InputTuple,
    TokenWithdrawnEvent.OutputTuple,
    TokenWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TransferExecuted"
  ): TypedContractEvent<
    TransferExecutedEvent.InputTuple,
    TransferExecutedEvent.OutputTuple,
    TransferExecutedEvent.OutputObject
  >;

  filters: {
    "AllowedAssetUpdated(address,bool)": TypedContractEvent<
      AllowedAssetUpdatedEvent.InputTuple,
      AllowedAssetUpdatedEvent.OutputTuple,
      AllowedAssetUpdatedEvent.OutputObject
    >;
    AllowedAssetUpdated: TypedContractEvent<
      AllowedAssetUpdatedEvent.InputTuple,
      AllowedAssetUpdatedEvent.OutputTuple,
      AllowedAssetUpdatedEvent.OutputObject
    >;

    "AllowedProtocolUpdated(address,bool)": TypedContractEvent<
      AllowedProtocolUpdatedEvent.InputTuple,
      AllowedProtocolUpdatedEvent.OutputTuple,
      AllowedProtocolUpdatedEvent.OutputObject
    >;
    AllowedProtocolUpdated: TypedContractEvent<
      AllowedProtocolUpdatedEvent.InputTuple,
      AllowedProtocolUpdatedEvent.OutputTuple,
      AllowedProtocolUpdatedEvent.OutputObject
    >;

    "ControllerUpdated(address)": TypedContractEvent<
      ControllerUpdatedEvent.InputTuple,
      ControllerUpdatedEvent.OutputTuple,
      ControllerUpdatedEvent.OutputObject
    >;
    ControllerUpdated: TypedContractEvent<
      ControllerUpdatedEvent.InputTuple,
      ControllerUpdatedEvent.OutputTuple,
      ControllerUpdatedEvent.OutputObject
    >;

    "LeaseContextUpdated(string,string,string)": TypedContractEvent<
      LeaseContextUpdatedEvent.InputTuple,
      LeaseContextUpdatedEvent.OutputTuple,
      LeaseContextUpdatedEvent.OutputObject
    >;
    LeaseContextUpdated: TypedContractEvent<
      LeaseContextUpdatedEvent.InputTuple,
      LeaseContextUpdatedEvent.OutputTuple,
      LeaseContextUpdatedEvent.OutputObject
    >;

    "MemberPolicyUpdated(address,bool,uint128,uint128)": TypedContractEvent<
      MemberPolicyUpdatedEvent.InputTuple,
      MemberPolicyUpdatedEvent.OutputTuple,
      MemberPolicyUpdatedEvent.OutputObject
    >;
    MemberPolicyUpdated: TypedContractEvent<
      MemberPolicyUpdatedEvent.InputTuple,
      MemberPolicyUpdatedEvent.OutputTuple,
      MemberPolicyUpdatedEvent.OutputObject
    >;

    "MemberSpendConsumed(address,string,uint128,uint128)": TypedContractEvent<
      MemberSpendConsumedEvent.InputTuple,
      MemberSpendConsumedEvent.OutputTuple,
      MemberSpendConsumedEvent.OutputObject
    >;
    MemberSpendConsumed: TypedContractEvent<
      MemberSpendConsumedEvent.InputTuple,
      MemberSpendConsumedEvent.OutputTuple,
      MemberSpendConsumedEvent.OutputObject
    >;

    "NativeWithdrawn(address,uint256)": TypedContractEvent<
      NativeWithdrawnEvent.InputTuple,
      NativeWithdrawnEvent.OutputTuple,
      NativeWithdrawnEvent.OutputObject
    >;
    NativeWithdrawn: TypedContractEvent<
      NativeWithdrawnEvent.InputTuple,
      NativeWithdrawnEvent.OutputTuple,
      NativeWithdrawnEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProtocolCallExecuted(string,string,address,uint256,uint128)": TypedContractEvent<
      ProtocolCallExecutedEvent.InputTuple,
      ProtocolCallExecutedEvent.OutputTuple,
      ProtocolCallExecutedEvent.OutputObject
    >;
    ProtocolCallExecuted: TypedContractEvent<
      ProtocolCallExecutedEvent.InputTuple,
      ProtocolCallExecutedEvent.OutputTuple,
      ProtocolCallExecutedEvent.OutputObject
    >;

    "TokenDeposited(address,address,uint256)": TypedContractEvent<
      TokenDepositedEvent.InputTuple,
      TokenDepositedEvent.OutputTuple,
      TokenDepositedEvent.OutputObject
    >;
    TokenDeposited: TypedContractEvent<
      TokenDepositedEvent.InputTuple,
      TokenDepositedEvent.OutputTuple,
      TokenDepositedEvent.OutputObject
    >;

    "TokenWithdrawn(address,address,uint256)": TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;
    TokenWithdrawn: TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;

    "TransferExecuted(string,string,address,address,uint256,uint128)": TypedContractEvent<
      TransferExecutedEvent.InputTuple,
      TransferExecutedEvent.OutputTuple,
      TransferExecutedEvent.OutputObject
    >;
    TransferExecuted: TypedContractEvent<
      TransferExecutedEvent.InputTuple,
      TransferExecutedEvent.OutputTuple,
      TransferExecutedEvent.OutputObject
    >;
  };
}
