/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BoundlessVault } from "./BoundlessVault";
export type { ITrustLeaseController } from "./ITrustLeaseController";
