/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ITrustLeaseControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canExecute"
      | "enforceAndConsume"
      | "getActiveLeaseByConsumer"
      | "getOperator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "canExecute",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enforceAndConsume",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveLeaseByConsumer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getOperator", values: [string]): string;

  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enforceAndConsume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveLeaseByConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperator",
    data: BytesLike
  ): Result;
}

export interface ITrustLeaseController extends BaseContract {
  connect(runner?: ContractRunner | null): ITrustLeaseController;
  waitForDeployment(): Promise<this>;

  interface: ITrustLeaseControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canExecute: TypedContractMethod<
    [leaseId: string, requestedUsd6: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        allowed: boolean;
        resolvedStatus: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;

  enforceAndConsume: TypedContractMethod<
    [leaseId: string, requestId: string, requestedUsd6: BigNumberish],
    [[bigint, bigint] & { resolvedStatus: bigint; remainingDailyUsd6: bigint }],
    "nonpayable"
  >;

  getActiveLeaseByConsumer: TypedContractMethod<
    [consumerName: string],
    [
      [
        boolean,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        exists: boolean;
        leaseId_: string;
        wallet: string;
        consumerName_: string;
        baseAsset: string;
        issuedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        spentWindowStartedAt: bigint;
        remainingDailyUsd6: bigint;
        policyHash: string;
        notesHash: string;
      }
    ],
    "view"
  >;

  getOperator: TypedContractMethod<
    [operatorName: string],
    [
      [boolean, string, bigint, bigint, string, string] & {
        exists: boolean;
        operatorName_: string;
        mode: bigint;
        updatedAt: bigint;
        noteHash: string;
        updater: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<
    [leaseId: string, requestedUsd6: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        allowed: boolean;
        resolvedStatus: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "enforceAndConsume"
  ): TypedContractMethod<
    [leaseId: string, requestId: string, requestedUsd6: BigNumberish],
    [[bigint, bigint] & { resolvedStatus: bigint; remainingDailyUsd6: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveLeaseByConsumer"
  ): TypedContractMethod<
    [consumerName: string],
    [
      [
        boolean,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        exists: boolean;
        leaseId_: string;
        wallet: string;
        consumerName_: string;
        baseAsset: string;
        issuedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        spentWindowStartedAt: bigint;
        remainingDailyUsd6: bigint;
        policyHash: string;
        notesHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOperator"
  ): TypedContractMethod<
    [operatorName: string],
    [
      [boolean, string, bigint, bigint, string, string] & {
        exists: boolean;
        operatorName_: string;
        mode: bigint;
        updatedAt: bigint;
        noteHash: string;
        updater: string;
      }
    ],
    "view"
  >;

  filters: {};
}
