/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  MockProtocolTarget,
  MockProtocolTargetInterface,
} from "../MockProtocolTarget";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "tag",
        type: "bytes32",
      },
    ],
    name: "Pinged",
    type: "event",
  },
  {
    inputs: [],
    name: "lastTag",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "tag",
        type: "bytes32",
      },
    ],
    name: "ping",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "pingCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610193908161001c8239f35b600080fdfe60806040818152600436101561001457600080fd5b600091823560e01c9081630698baa4146101415750806333d425c41461008b578063431838341461006d5763877045691461004e57600080fd5b34610069578160031936011261006957602091549051908152f35b5080fd5b50346100695781600319360112610069576020906001549051908152f35b5090602036600319011261013e5760043581546001810180911161012a5780835534600155816002558184513481527f14bdd0b20af19cbd3bdad0aac65f60da2b18a0a01496f93f0bd3af5e8a37639960203392a38351906020820192835284820152838152606081019281841067ffffffffffffffff851117610116575082602094525190208152f35b634e487b7160e01b81526041600452602490fd5b634e487b7160e01b83526011600452602483fd5b80fd5b8390346100695781600319360112610069576020906002548152f3fea264697066735822122056334dfe2f2fc38031ff1ff83f56caf83231e8dd36a607b38848e796bdc4182164736f6c63430008180033";

type MockProtocolTargetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockProtocolTargetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockProtocolTarget__factory extends ContractFactory {
  constructor(...args: MockProtocolTargetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockProtocolTarget & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockProtocolTarget__factory {
    return super.connect(runner) as MockProtocolTarget__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockProtocolTargetInterface {
    return new Interface(_abi) as MockProtocolTargetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockProtocolTarget {
    return new Contract(address, _abi, runner) as unknown as MockProtocolTarget;
  }
}
