/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BoundlessVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BoundlessVault__factory>;
    getContractFactory(
      name: "ITrustLeaseController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITrustLeaseController__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "MockProtocolTarget",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockProtocolTarget__factory>;
    getContractFactory(
      name: "TrustLeaseController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustLeaseController__factory>;

    getContractAt(
      name: "BoundlessVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BoundlessVault>;
    getContractAt(
      name: "ITrustLeaseController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITrustLeaseController>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "MockProtocolTarget",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockProtocolTarget>;
    getContractAt(
      name: "TrustLeaseController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustLeaseController>;

    deployContract(
      name: "BoundlessVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BoundlessVault>;
    deployContract(
      name: "ITrustLeaseController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITrustLeaseController>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockProtocolTarget",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockProtocolTarget>;
    deployContract(
      name: "TrustLeaseController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustLeaseController>;

    deployContract(
      name: "BoundlessVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BoundlessVault>;
    deployContract(
      name: "ITrustLeaseController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITrustLeaseController>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockProtocolTarget",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockProtocolTarget>;
    deployContract(
      name: "TrustLeaseController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustLeaseController>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
