/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as boundlessVaultSol from "./BoundlessVault.sol";
export type { boundlessVaultSol };
export type { MockERC20 } from "./MockERC20";
export type { MockProtocolTarget } from "./MockProtocolTarget";
export type { TrustLeaseController } from "./TrustLeaseController";
export * as factories from "./factories";
export type { BoundlessVault } from "./BoundlessVault.sol/BoundlessVault";
export { BoundlessVault__factory } from "./factories/BoundlessVault.sol/BoundlessVault__factory";
export type { ITrustLeaseController } from "./BoundlessVault.sol/ITrustLeaseController";
export { ITrustLeaseController__factory } from "./factories/BoundlessVault.sol/ITrustLeaseController__factory";
export { MockERC20__factory } from "./factories/MockERC20__factory";
export { MockProtocolTarget__factory } from "./factories/MockProtocolTarget__factory";
export { TrustLeaseController__factory } from "./factories/TrustLeaseController__factory";
