/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MockProtocolTargetInterface extends Interface {
  getFunction(
    nameOrSignature: "lastTag" | "lastValue" | "ping" | "pingCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Pinged"): EventFragment;

  encodeFunctionData(functionFragment: "lastTag", values?: undefined): string;
  encodeFunctionData(functionFragment: "lastValue", values?: undefined): string;
  encodeFunctionData(functionFragment: "ping", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "pingCount", values?: undefined): string;

  decodeFunctionResult(functionFragment: "lastTag", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pingCount", data: BytesLike): Result;
}

export namespace PingedEvent {
  export type InputTuple = [
    caller: AddressLike,
    value: BigNumberish,
    tag: BytesLike
  ];
  export type OutputTuple = [caller: string, value: bigint, tag: string];
  export interface OutputObject {
    caller: string;
    value: bigint;
    tag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockProtocolTarget extends BaseContract {
  connect(runner?: ContractRunner | null): MockProtocolTarget;
  waitForDeployment(): Promise<this>;

  interface: MockProtocolTargetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lastTag: TypedContractMethod<[], [string], "view">;

  lastValue: TypedContractMethod<[], [bigint], "view">;

  ping: TypedContractMethod<[tag: BytesLike], [string], "payable">;

  pingCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lastTag"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ping"
  ): TypedContractMethod<[tag: BytesLike], [string], "payable">;
  getFunction(
    nameOrSignature: "pingCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Pinged"
  ): TypedContractEvent<
    PingedEvent.InputTuple,
    PingedEvent.OutputTuple,
    PingedEvent.OutputObject
  >;

  filters: {
    "Pinged(address,uint256,bytes32)": TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;
    Pinged: TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;
  };
}
