/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TrustLeaseControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeLeaseKeyByConsumer"
      | "anchorReceipt"
      | "authorizedExecutors"
      | "canExecute"
      | "consumedSpendUsd6ByRequest"
      | "consumerKey"
      | "enforceAndConsume"
      | "getActiveLeaseByConsumer"
      | "getLatestReceiptByConsumer"
      | "getOperator"
      | "issueLease"
      | "latestReceiptKeyByConsumer"
      | "leaseKey"
      | "operatorKey"
      | "owner"
      | "requestKey"
      | "setExecutor"
      | "setLeaseStatus"
      | "setOperatorMode"
      | "totalBlockedReceipts"
      | "totalBroadcastedReceipts"
      | "totalLeasesIssued"
      | "totalReceiptsAnchored"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutorAuthorizationUpdated"
      | "LeaseBudgetConsumed"
      | "LeaseIssued"
      | "LeaseStatusChanged"
      | "OperatorModeChanged"
      | "OwnershipTransferred"
      | "ReceiptAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeLeaseKeyByConsumer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorReceipt",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedExecutors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canExecute",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "consumedSpendUsd6ByRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "consumerKey", values: [string]): string;
  encodeFunctionData(
    functionFragment: "enforceAndConsume",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveLeaseByConsumer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestReceiptByConsumer",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getOperator", values: [string]): string;
  encodeFunctionData(
    functionFragment: "issueLease",
    values: [
      string,
      string,
      AddressLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "latestReceiptKeyByConsumer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "leaseKey", values: [string]): string;
  encodeFunctionData(functionFragment: "operatorKey", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "requestKey", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setExecutor",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setLeaseStatus",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperatorMode",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBlockedReceipts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBroadcastedReceipts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLeasesIssued",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalReceiptsAnchored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeLeaseKeyByConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "consumedSpendUsd6ByRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consumerKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforceAndConsume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveLeaseByConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestReceiptByConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issueLease", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestReceiptKeyByConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leaseKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operatorKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "requestKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLeaseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperatorMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBlockedReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBroadcastedReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLeasesIssued",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReceiptsAnchored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ExecutorAuthorizationUpdatedEvent {
  export type InputTuple = [executor: AddressLike, allowed: boolean];
  export type OutputTuple = [executor: string, allowed: boolean];
  export interface OutputObject {
    executor: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseBudgetConsumedEvent {
  export type InputTuple = [
    leaseKey: BytesLike,
    requestKey: BytesLike,
    leaseId: string,
    requestId: string,
    spentUsd6: BigNumberish,
    remainingDailyUsd6: BigNumberish
  ];
  export type OutputTuple = [
    leaseKey: string,
    requestKey: string,
    leaseId: string,
    requestId: string,
    spentUsd6: bigint,
    remainingDailyUsd6: bigint
  ];
  export interface OutputObject {
    leaseKey: string;
    requestKey: string;
    leaseId: string;
    requestId: string;
    spentUsd6: bigint;
    remainingDailyUsd6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseIssuedEvent {
  export type InputTuple = [
    leaseKey: BytesLike,
    leaseId: string,
    consumerKey: BytesLike,
    wallet: AddressLike,
    expiresAt: BigNumberish,
    perTxUsd6: BigNumberish,
    dailyBudgetUsd6: BigNumberish,
    policyHash: BytesLike
  ];
  export type OutputTuple = [
    leaseKey: string,
    leaseId: string,
    consumerKey: string,
    wallet: string,
    expiresAt: bigint,
    perTxUsd6: bigint,
    dailyBudgetUsd6: bigint,
    policyHash: string
  ];
  export interface OutputObject {
    leaseKey: string;
    leaseId: string;
    consumerKey: string;
    wallet: string;
    expiresAt: bigint;
    perTxUsd6: bigint;
    dailyBudgetUsd6: bigint;
    policyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LeaseStatusChangedEvent {
  export type InputTuple = [
    leaseKey: BytesLike,
    leaseId: string,
    status: BigNumberish,
    noteHash: BytesLike,
    changedAt: BigNumberish
  ];
  export type OutputTuple = [
    leaseKey: string,
    leaseId: string,
    status: bigint,
    noteHash: string,
    changedAt: bigint
  ];
  export interface OutputObject {
    leaseKey: string;
    leaseId: string;
    status: bigint;
    noteHash: string;
    changedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorModeChangedEvent {
  export type InputTuple = [
    operatorKey: BytesLike,
    operatorName: string,
    mode: BigNumberish,
    noteHash: BytesLike,
    changedAt: BigNumberish
  ];
  export type OutputTuple = [
    operatorKey: string,
    operatorName: string,
    mode: bigint,
    noteHash: string,
    changedAt: bigint
  ];
  export interface OutputObject {
    operatorKey: string;
    operatorName: string;
    mode: bigint;
    noteHash: string;
    changedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptAnchoredEvent {
  export type InputTuple = [
    requestKey: BytesLike,
    consumerKey: BytesLike,
    leaseId: string,
    requestId: string,
    outcome: BigNumberish,
    executionStatus: BigNumberish,
    spentUsd6: BigNumberish,
    txHash: BytesLike,
    proofHash: BytesLike
  ];
  export type OutputTuple = [
    requestKey: string,
    consumerKey: string,
    leaseId: string,
    requestId: string,
    outcome: bigint,
    executionStatus: bigint,
    spentUsd6: bigint,
    txHash: string,
    proofHash: string
  ];
  export interface OutputObject {
    requestKey: string;
    consumerKey: string;
    leaseId: string;
    requestId: string;
    outcome: bigint;
    executionStatus: bigint;
    spentUsd6: bigint;
    txHash: string;
    proofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustLeaseController extends BaseContract {
  connect(runner?: ContractRunner | null): TrustLeaseController;
  waitForDeployment(): Promise<this>;

  interface: TrustLeaseControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeLeaseKeyByConsumer: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  anchorReceipt: TypedContractMethod<
    [
      leaseId: string,
      requestId: string,
      consumerName: string,
      outcome: BigNumberish,
      executionStatus: BigNumberish,
      spentUsd6: BigNumberish,
      txHash: BytesLike,
      proofHash: BytesLike,
      artifactUri: string
    ],
    [string],
    "nonpayable"
  >;

  authorizedExecutors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  canExecute: TypedContractMethod<
    [leaseId: string, requestedUsd6: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        allowed: boolean;
        resolvedStatus: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;

  consumedSpendUsd6ByRequest: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  consumerKey: TypedContractMethod<[consumerName: string], [string], "view">;

  enforceAndConsume: TypedContractMethod<
    [leaseId: string, requestId: string, requestedUsd6: BigNumberish],
    [[bigint, bigint] & { resolvedStatus: bigint; remainingDailyUsd6: bigint }],
    "nonpayable"
  >;

  getActiveLeaseByConsumer: TypedContractMethod<
    [consumerName: string],
    [
      [
        boolean,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        exists: boolean;
        leaseId_: string;
        wallet: string;
        consumerName_: string;
        baseAsset: string;
        issuedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        spentWindowStartedAt: bigint;
        remainingDailyUsd6: bigint;
        policyHash: string;
        notesHash: string;
      }
    ],
    "view"
  >;

  getLatestReceiptByConsumer: TypedContractMethod<
    [consumerName: string],
    [
      [
        boolean,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        exists: boolean;
        leaseId_: string;
        requestId_: string;
        consumerName_: string;
        outcome: bigint;
        executionStatus: bigint;
        spentUsd6: bigint;
        txHash: string;
        proofHash: string;
        artifactUri: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getOperator: TypedContractMethod<
    [operatorName: string],
    [
      [boolean, string, bigint, bigint, string, string] & {
        exists: boolean;
        operatorName_: string;
        mode: bigint;
        updatedAt: bigint;
        noteHash: string;
        updater: string;
      }
    ],
    "view"
  >;

  issueLease: TypedContractMethod<
    [
      leaseId: string,
      consumerName: string,
      wallet: AddressLike,
      baseAsset: string,
      expiresAt: BigNumberish,
      perTxUsd6: BigNumberish,
      dailyBudgetUsd6: BigNumberish,
      policyHash: BytesLike,
      notesHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  latestReceiptKeyByConsumer: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  leaseKey: TypedContractMethod<[leaseId: string], [string], "view">;

  operatorKey: TypedContractMethod<[operatorName: string], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  requestKey: TypedContractMethod<[requestId: string], [string], "view">;

  setExecutor: TypedContractMethod<
    [executor: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setLeaseStatus: TypedContractMethod<
    [leaseId: string, status: BigNumberish, noteHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setOperatorMode: TypedContractMethod<
    [operatorName: string, mode: BigNumberish, noteHash: BytesLike],
    [void],
    "nonpayable"
  >;

  totalBlockedReceipts: TypedContractMethod<[], [bigint], "view">;

  totalBroadcastedReceipts: TypedContractMethod<[], [bigint], "view">;

  totalLeasesIssued: TypedContractMethod<[], [bigint], "view">;

  totalReceiptsAnchored: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeLeaseKeyByConsumer"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "anchorReceipt"
  ): TypedContractMethod<
    [
      leaseId: string,
      requestId: string,
      consumerName: string,
      outcome: BigNumberish,
      executionStatus: BigNumberish,
      spentUsd6: BigNumberish,
      txHash: BytesLike,
      proofHash: BytesLike,
      artifactUri: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedExecutors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<
    [leaseId: string, requestedUsd6: BigNumberish],
    [
      [boolean, bigint, bigint] & {
        allowed: boolean;
        resolvedStatus: bigint;
        remainingDailyUsd6: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "consumedSpendUsd6ByRequest"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "consumerKey"
  ): TypedContractMethod<[consumerName: string], [string], "view">;
  getFunction(
    nameOrSignature: "enforceAndConsume"
  ): TypedContractMethod<
    [leaseId: string, requestId: string, requestedUsd6: BigNumberish],
    [[bigint, bigint] & { resolvedStatus: bigint; remainingDailyUsd6: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveLeaseByConsumer"
  ): TypedContractMethod<
    [consumerName: string],
    [
      [
        boolean,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        exists: boolean;
        leaseId_: string;
        wallet: string;
        consumerName_: string;
        baseAsset: string;
        issuedAt: bigint;
        expiresAt: bigint;
        status: bigint;
        perTxUsd6: bigint;
        dailyBudgetUsd6: bigint;
        spentTodayUsd6: bigint;
        spentWindowStartedAt: bigint;
        remainingDailyUsd6: bigint;
        policyHash: string;
        notesHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestReceiptByConsumer"
  ): TypedContractMethod<
    [consumerName: string],
    [
      [
        boolean,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint
      ] & {
        exists: boolean;
        leaseId_: string;
        requestId_: string;
        consumerName_: string;
        outcome: bigint;
        executionStatus: bigint;
        spentUsd6: bigint;
        txHash: string;
        proofHash: string;
        artifactUri: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOperator"
  ): TypedContractMethod<
    [operatorName: string],
    [
      [boolean, string, bigint, bigint, string, string] & {
        exists: boolean;
        operatorName_: string;
        mode: bigint;
        updatedAt: bigint;
        noteHash: string;
        updater: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueLease"
  ): TypedContractMethod<
    [
      leaseId: string,
      consumerName: string,
      wallet: AddressLike,
      baseAsset: string,
      expiresAt: BigNumberish,
      perTxUsd6: BigNumberish,
      dailyBudgetUsd6: BigNumberish,
      policyHash: BytesLike,
      notesHash: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "latestReceiptKeyByConsumer"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "leaseKey"
  ): TypedContractMethod<[leaseId: string], [string], "view">;
  getFunction(
    nameOrSignature: "operatorKey"
  ): TypedContractMethod<[operatorName: string], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestKey"
  ): TypedContractMethod<[requestId: string], [string], "view">;
  getFunction(
    nameOrSignature: "setExecutor"
  ): TypedContractMethod<
    [executor: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLeaseStatus"
  ): TypedContractMethod<
    [leaseId: string, status: BigNumberish, noteHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperatorMode"
  ): TypedContractMethod<
    [operatorName: string, mode: BigNumberish, noteHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalBlockedReceipts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalBroadcastedReceipts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLeasesIssued"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalReceiptsAnchored"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExecutorAuthorizationUpdated"
  ): TypedContractEvent<
    ExecutorAuthorizationUpdatedEvent.InputTuple,
    ExecutorAuthorizationUpdatedEvent.OutputTuple,
    ExecutorAuthorizationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseBudgetConsumed"
  ): TypedContractEvent<
    LeaseBudgetConsumedEvent.InputTuple,
    LeaseBudgetConsumedEvent.OutputTuple,
    LeaseBudgetConsumedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseIssued"
  ): TypedContractEvent<
    LeaseIssuedEvent.InputTuple,
    LeaseIssuedEvent.OutputTuple,
    LeaseIssuedEvent.OutputObject
  >;
  getEvent(
    key: "LeaseStatusChanged"
  ): TypedContractEvent<
    LeaseStatusChangedEvent.InputTuple,
    LeaseStatusChangedEvent.OutputTuple,
    LeaseStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorModeChanged"
  ): TypedContractEvent<
    OperatorModeChangedEvent.InputTuple,
    OperatorModeChangedEvent.OutputTuple,
    OperatorModeChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptAnchored"
  ): TypedContractEvent<
    ReceiptAnchoredEvent.InputTuple,
    ReceiptAnchoredEvent.OutputTuple,
    ReceiptAnchoredEvent.OutputObject
  >;

  filters: {
    "ExecutorAuthorizationUpdated(address,bool)": TypedContractEvent<
      ExecutorAuthorizationUpdatedEvent.InputTuple,
      ExecutorAuthorizationUpdatedEvent.OutputTuple,
      ExecutorAuthorizationUpdatedEvent.OutputObject
    >;
    ExecutorAuthorizationUpdated: TypedContractEvent<
      ExecutorAuthorizationUpdatedEvent.InputTuple,
      ExecutorAuthorizationUpdatedEvent.OutputTuple,
      ExecutorAuthorizationUpdatedEvent.OutputObject
    >;

    "LeaseBudgetConsumed(bytes32,bytes32,string,string,uint128,uint128)": TypedContractEvent<
      LeaseBudgetConsumedEvent.InputTuple,
      LeaseBudgetConsumedEvent.OutputTuple,
      LeaseBudgetConsumedEvent.OutputObject
    >;
    LeaseBudgetConsumed: TypedContractEvent<
      LeaseBudgetConsumedEvent.InputTuple,
      LeaseBudgetConsumedEvent.OutputTuple,
      LeaseBudgetConsumedEvent.OutputObject
    >;

    "LeaseIssued(bytes32,string,bytes32,address,uint64,uint128,uint128,bytes32)": TypedContractEvent<
      LeaseIssuedEvent.InputTuple,
      LeaseIssuedEvent.OutputTuple,
      LeaseIssuedEvent.OutputObject
    >;
    LeaseIssued: TypedContractEvent<
      LeaseIssuedEvent.InputTuple,
      LeaseIssuedEvent.OutputTuple,
      LeaseIssuedEvent.OutputObject
    >;

    "LeaseStatusChanged(bytes32,string,uint8,bytes32,uint64)": TypedContractEvent<
      LeaseStatusChangedEvent.InputTuple,
      LeaseStatusChangedEvent.OutputTuple,
      LeaseStatusChangedEvent.OutputObject
    >;
    LeaseStatusChanged: TypedContractEvent<
      LeaseStatusChangedEvent.InputTuple,
      LeaseStatusChangedEvent.OutputTuple,
      LeaseStatusChangedEvent.OutputObject
    >;

    "OperatorModeChanged(bytes32,string,uint8,bytes32,uint64)": TypedContractEvent<
      OperatorModeChangedEvent.InputTuple,
      OperatorModeChangedEvent.OutputTuple,
      OperatorModeChangedEvent.OutputObject
    >;
    OperatorModeChanged: TypedContractEvent<
      OperatorModeChangedEvent.InputTuple,
      OperatorModeChangedEvent.OutputTuple,
      OperatorModeChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReceiptAnchored(bytes32,bytes32,string,string,uint8,uint8,uint128,bytes32,bytes32)": TypedContractEvent<
      ReceiptAnchoredEvent.InputTuple,
      ReceiptAnchoredEvent.OutputTuple,
      ReceiptAnchoredEvent.OutputObject
    >;
    ReceiptAnchored: TypedContractEvent<
      ReceiptAnchoredEvent.InputTuple,
      ReceiptAnchoredEvent.OutputTuple,
      ReceiptAnchoredEvent.OutputObject
    >;
  };
}
